sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=stakelovelace/cardano-htn
before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker build --compress -t "${IMAGE_NAME}:stage2" .

after_script:

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:stage2"
  on:
    branch: stage2

include: 
  - stage: trigger downstream
    jdk: oraclejdk8
    script: |
      echo 'TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST'
      if [[ ($TRAVIS_BRANCH == master) &&
            ($TRAVIS_PULL_REQUEST == false) ]] ; then
        curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
        sh trigger-travis.sh stakelovelace cardano-htn $TRAVIS_ACCESS_TOKEN
      fi
