name: Docker Image CD Stage 3

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: dockerfile Stage2 Download
      run: |
        curl -sLo Dockerstage3 https://raw.githubusercontent.com/stakelovelace/cardano-htn/stage3/Dockerfile
    - name: Compiling new node software
      run: |      
        docker build . --file Dockerstage3 --compress --tag stakelovelace/cardano-htn:stage3
    - name: docker push
      run: |
        docker push stakelovelace/cardano-htn:stage3
        docker tag stakelovelace/cardano-htn:stage3 stakelovelace/cardano-node:latest
        docker tag stakelovelace/cardano-htn:stage3 cardanocommunity/cardano-node:stage3
        docker tag stakelovelace/cardano-htn:stage3 cardanocommunity/cardano-node:latest
        docker push stakelovelace/cardano-node:latest
     - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER2 }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD2 }}  
      run: |
        docker login -u $DOCKER_USER2 -p $DOCKER_PASSWORD2
    - name: docker push
      run: |
        docker push cardanocommunity/cardano-node:stage3
        docker push cardanocommunity/cardano-node:latest
