name: Docker Image CD Stage 1

on:
  workflow_dispatch:
  push:
    paths:
      - 'release-versions/guild-prereq-latest.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USER2: ${{ secrets.DOCKER_USER2 }}   
        DOCKER_PASSWORD2: ${{ secrets.DOCKER_PASSWORD2 }} 
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Compiling new node software
      run: |      
        docker build . --compress --tag stakelovelace/cardano-htn:stage1
    - name: docker push stakelovelace
      run: |
        docker push stakelovelace/cardano-htn:stage1
        docker logout
    - name: docker push cardanocommunity
      run: |
        docker login -u $DOCKER_USER2 -p $DOCKER_PASSWORD2
    - name: docker push
      run: |
        docker push cardanocommunity/cardano-node:stage1
    - name: docker build trigger stage2
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER}}:${{secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/stakelovelace/cardano-htn/actions/workflows/docker-stage2.yml/dispatches --data '{"ref": "master"}'
