name: Docker Image CD Stage 2

on:
  workflow_dispatch:
  push:
    paths:
      - 'release-versions/cardano-node-latest.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login 
      run: |
        docker login -u ${{ secrets.DOCKER_USER }}  -p ${{ secrets.DOCKER_PASSWORD }} 
    - name: dockerfile Stage2 Download
      run: |
        curl -sLo Dockerstage2 https://raw.githubusercontent.com/stakelovelace/cardano-htn/stage2/Dockerfile ;
    - name: Compiling new node software
      run: |      
        docker build . --file Dockerstage2 --compress --tag stakelovelace/cardano-htn:stage2
    - name: docker push
      run: |
        docker push stakelovelace/cardano-htn:stage2
    - name: docker push
      run: |
        curl -XPOST -u "${{ secrets.REPO_SCOPED_USER}}:${{secrets.REPO_SCOPED_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/stakelovelace/cardano-htn/actions/workflows/docker-stage3.yml/dispatches --data '{"ref": "master"}'
