name: Docker Image CD Stage 3

#on: 
  #workflow_dispatch:
  #push:
  #   paths:
  #    - 'release-versions/guild-prereq-latest.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}  
    - name: dockerfile Stage2 Download
      run: |
        curl -sLo Dockerstage3 https://raw.githubusercontent.com/stakelovelace/cardano-htn/master/Dockerfile
    - name: Compiling new node software suite
      run: |      
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Compiling new node software
      run: |
        DOCKER_BUILDKIT=1 docker build . --file Dockerstage3 --compress --tag stakelovelace/cardano-htn:stage3
    - name: docker push Cardano HTN
      run: |
        docker push stakelovelace/cardano-htn:stage3
    - name: docker push Cardano Node
      run: |
        CNVERSION=`cat release-versions/cardano-node-latest.txt`
        docker tag  stakelovelace/cardano-htn:stage3 stakelovelace/cardano-node:latest 
        docker tag  stakelovelace/cardano-htn:stage3 stakelovelace/cardano-node:$CNVERSION
        docker push stakelovelace/cardano-node:latest
        docker push stakelovelace/cardano-node:$CNVERSION
