name: Docker Image CD Stage 3

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}  
    - name: dockerfile Stage2 Download
      run: |
        curl -sLo Dockerstage3 https://raw.githubusercontent.com/stakelovelace/cardano-htn/stage3/Dockerfile
    - name: Compiling new node software
      run: |      
        DOCKER_BUILDKIT=1 docker build . --file Dockerstage3 --compress --tag stakelovelace/cardano-htn:stage3 --tag stakelovelace/cardano-node:latest
    - name: docker push Cardano HTN
      run: |
        docker push stakelovelace/cardano-htn:stage3
    - name: docker push Cardano Node
      run: |
        VERSION=`cat release-versions/guild-prereq-latest.txt`
        docker push stakelovelace/cardano-node:latest
        docker push stakelovelace/cardano-node:$VERSION
