name: Docker P2P

on:
  workflow_dispatch:
  push:
    paths:
      - 'release-versions/guild-prereq-latest.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_USER }}  -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Compiling new node software
      run: |      
        DOCKER_BUILDKIT=1 docker build --compress -t stakelovelace/cardano-node:latest - < Dockerfile
    - name: docker push Cardano Node
      run: |
        CNVERSION=`cat release-versions/cardano-node-latest.txt`
        docker tag  stakelovelace/cardano-node:latest stakelovelace/cardano-node:$CNVERSION
        docker push stakelovelace/cardano-node:latest
        docker push stakelovelace/cardano-node:$CNVERSION
